name: Bust Caches

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      # You can test your matrix by printing the current Python version
      - name: Test
        run: python ".github/workflows/cache_buster.py" --noinput
